# Generated by Django 3.1.11 on 2021-05-16 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('language', models.BooleanField(default=False)),
                ('code', models.BooleanField(default=False)),
                ('has_completed', models.BooleanField(default=False)),
                ('last_submission', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'ordering': ('-has_completed', 'last_submission', '-code', '-has_completed'),
            },
        ),
    ]
